name: Non Function Edit Approve
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    paths:
      - "README.md"
jobs:
  approve-merge:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if only README is updated
        id: diff
        run: |
          git diff --name-only "origin/main" HEAD | tee /tmp/diff_files
          if [ "$(wc -l < /tmp/diff_files)" -eq "$(grep -c "^README.md$" /tmp/diff_files)" ]; then
            echo "only_readme=yes" >> $GITHUB_OUTPUT
          else
            echo "only_readme=no" >> $GITHUB_OUTPUT
          fi

      - name: Approve PR
        if: ${{ steps.diff.outputs.only_readme == 'yes' }}
        id: approve
        run: |
          gh pr comment $PR_NUMBER -b "The change is only README.md. I approve automatically."
          gh pr review $PR_NUMBER --approve
          echo "is_approved=yes" >> $GITHUB_OUTPUT

      - name: Merge the PR
        if: ${{ steps.approve.outputs.is_approved == 'yes' }}
        run: |
          gh pr merge $PR_NUMBER -s -d
