name: Comment Triggered Approve for non-function and README

on:
  issue_comment:
    types:
      - created

jobs:
  check_change:
    if: >-
      ${{ 
        github.event.comment.body == 'approve me' && 
        github.event.comment.user.login == vars.OWNER && 
        github.event.issue.pull_request 
      }}

    runs-on: ubuntu-latest

    env:
      PR_NUMBER: ${{ github.event.issue.number }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Check diff files
        id: diff
        run: |
          git diff --name-only "origin/main" HEAD | tee /tmp/diff_files
          if [ "$(wc -l < /tmp/diff_files)" -eq  "$(grep -c -e "^README.md$" -e "^LICENSE.md$" -e ".github/*" -e "^.gitignore$" -e "^setup.py$" /tmp/diff_files)" ]; then
            echo "no_violation=yes" >> $GITHUB_OUTPUT
          else
            echo "no_violation=no" >> $GITHUB_OUTPUT
          fi

      - name: Approve if no-violation
        if: ${{ steps.diff.outputs.no_violation == 'yes' }}
        run: |
          gh pr comment $PR_NUMBER -b "The change can approve automatically."
          gh pr review $PR_NUMBER --approve
          echo "is_approved=yes" >> $GITHUB_OUTPUT

      - name: Reject the request
        if: ${{ steps.diff.outputs.no_violation == 'no' }}
        run: |
          gh pr comment $PR_NUMBER -b \
            "This approve request was rejected due to the change violate commented approve policy. 
            under 'marquetry' and 'test' changes can't be approved by this function."
          echo "::error::There are violate changes."
          exit 1
